### ISSUE TITLE
tracking arrow off by a few tiles

### ISSUE THREAD

**Issue by expiation** [ClassicUO/ClassicUO#545] opened 2019-06-25 18:04 UTC
**Describe the bug**
the below picture shows me tracking a person that is not moving, as you can see the tracking arrow is not pointing near his actual position

https://cdn.discordapp.com/attachments/553829720232558613/593137769958604841/unknown.png

**Comment by aclark13** [comment] 2019-06-25 18:17
Confirmed.  Arrow seems to be off 1 Y tile and about 5-6 X tiles

**Comment by andreakarasho** [comment] 2019-06-25 21:08
this dev build pls

**Comment by expiation** [comment] 2019-06-25 22:43
still seems off 

6:37:11 PM |  Trace   | Starting ClassicUO - 0.1.2.22

https://cdn.discordapp.com/attachments/553829720232558613/593209331025969154/unknown.png

**Comment by andreakarasho** [comment] 2019-07-05 21:02
should be fixed in dev. Can you confirm? I'll open it if it's still off

**Closed as completed by andreakarasho** 2019-07-05 21:02 UTC
Labels: bug
