### ISSUE TITLE
MovePlayer macro

### ISSUE THREAD

**Issue by natryl** [ClassicUO/ClassicUO#908] opened 2020-01-16 16:06 UTC
MovePlayer macro is not disabled with press enter to activate chat. So if you press enter to chat and then hit the keys mapped to moveplayer it moves you in game. Only the first key press moves the player, following key presses for the other movement directions do not move the player while in chat.

**Comment by andreakarasho** [comment] 2020-01-17 16:15
Pushed a fix to dev branch. Let me know if i can close this :)

**Comment by natryl** [comment] 2020-01-17 17:04
Same behavior still exist.

**Comment by andreakarasho** [comment] 2020-01-17 20:48
I see now that MovePlayer macro is an duplicate of the "Walk" macro.
I will push a patch to remove and replace this command with the Walk.

Stay tuned.

**Comment by andreakarasho** [comment] 2020-01-18 12:24
i added/edited some hotkey behaviour to a parallel branch.

When caret is focused to a different textbox [server gump or book] than chat one --> macro cannot be executed. Same for arrow keys.
Otherwise macro will be executed.
If  chat is focused and chat text is NOT empty the arrow keys will not move your char, but they allow you to navigate within the text


Just and edit: i'm working to don't execute macros when you need to press ENTER to activate chat

**Closed as completed** 2020-02-23 14:45 UTC
