### ISSUE TITLE
Vendor not showing correct name

### ISSUE THREAD

**Issue by BravoSierraUO** [ClassicUO/ClassicUO#405] opened 2019-04-05 05:25 UTC
**Describe the bug**
My vendor named "120 Food" is showing as "Food" - see screenshot

**To Reproduce**
1. Double Click Vendor - the hitpoint bar is missing the name
2. the name is correct when i "all names"
3. the name is correct when i open my vendor menu

**Expected behavior**
Vendors name should be "120 Food"

**Screenshots**
![image](https://user-images.githubusercontent.com/49131722/55605230-26f73b80-5739-11e9-975b-9c89ad9fb506.png)

**Comment by zolter** [comment] 2019-04-05 06:02
In original client you see numerics? version?

**Comment by BravoSierraUO** [comment] 2019-04-05 11:57
![image](https://user-images.githubusercontent.com/49131722/55626048-12826580-5770-11e9-9080-cb6bd01391a5.png)
 putting up a more complete png with several shops/gumps

**Comment by zolter** [comment] 2019-04-05 12:00
Client version?
Can you edit numbers in this window or write them yourself?

**Comment by zolter** [comment] 2019-04-05 12:04
The problem is that a player cannot use numbers in player and animal names. I think we should display numbers if there is no possibility to edit. Thanks, I'll fix it today!

**Comment by BravoSierraUO** [comment] 2019-04-05 12:09
![image](https://user-images.githubusercontent.com/49131722/55626655-ba4c6300-5771-11e9-92c7-b866254e46c4.png)

**Comment by zolter** [comment] 2019-04-05 12:11
"4/5" in original client -> "4 5"?

**Comment by BravoSierraUO** [comment] 2019-04-05 12:18
![image](https://user-images.githubusercontent.com/49131722/55627099-fc29d900-5772-11e9-8d9b-cf4a7cd498bb.png)
!Food worked with allnames too i just forgot to push it

**Comment by zolter** [comment] 2019-04-05 19:36
**There is 1 problem:** 

Original client deny enter special characters and numbers  (when editing the gump), but correctly displays them. If you try to change name in gump manually, you will not be able to save it until you delete all the numbers and special characters (special error message will be displayed). But you can easily use special characters and numbers (if your server permits) with the GM commands (.xname). But GM also cannot edit gump manually.

I hope I clearly described the situation))

I think this is very stupid behavior. If the server does not perform additional filtering - this is his server problem. Therefore, our system (classicuo) works differently and allows you to work correctly with numbers and special characters in health gump. If there are disagreements - tell about it and offer your own version.

**Comment by zolter** [comment] 2019-04-05 19:37
My change is already in dev, you can check and close this issue 👍

**Closed as completed** 2019-04-06 05:44 UTC
Labels: bug
